#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ "$current_branch" = "$protected_branch" ]; then
  echo "You are on branch $current_branch. Direct push to $protected_branch is not allowed."
  exit 1
fi

exit 0
